import os
import time
import logging
from google import genai
from google.genai import errors

logger = logging.getLogger(__name__)


class GeminiClient:
    """
    Client for interacting with the Google Gemini API using the new google-genai SDK.
    Handles communication, parameter validation, and retries for transient failures.
    """

    def __init__(
        self,
        api_key: str = None,
        model: str = "gemini-3.5-flash",
        max_retries: int = 3,
        initial_delay: float = 1.0,
    ):
        """
        Initialize the Gemini client.

        Parameters:
            api_key (str): Optional API key. If not provided, it will check the
                           GEMINI_API_KEY environment variable.
            model (str): Gemini model identifier (default: "gemini-3.5-flash").
            max_retries (int): Maximum number of retry attempts for transient errors.
            initial_delay (float): Initial delay in seconds for exponential backoff.
        """
        self.api_key = api_key or os.environ.get("GEMINI_API_KEY")
        self.model = model
        self.max_retries = max_retries
        self.initial_delay = initial_delay

        # Initialize the Client. If api_key is None, it defaults to the environment variable.
        if self.api_key:
            self.client = genai.Client(api_key=self.api_key)
        else:
            self.client = genai.Client()

    def generate_response(self, prompt: str) -> str:
        """
        Send a prompt to the Gemini API and return the textual response.
        Retries on transient errors (429, 500, 503, 504) with exponential backoff.

        Parameters:
            prompt (str): The prompt message to analyze.

        Returns:
            str: The text content generated by Gemini.

        Raises:
            ValueError: If the prompt is empty or the response text is empty.
            google.genai.errors.APIError: If a non-retryable API error occurs or
                                          max retries are exhausted.
        """
        if not isinstance(prompt, str) or not prompt.strip():
            raise ValueError("Prompt must be a non-empty string")

        delay = self.initial_delay
        for attempt in range(self.max_retries + 1):
            try:
                response = self.client.models.generate_content(
                    model=self.model,
                    contents=prompt,
                )
                # Verify that we got a valid text response
                if not response.text:
                    raise ValueError("Received empty response text from Gemini API")
                return response.text

            except errors.APIError as e:
                # Identify if the exception is transient and can be retried
                status_code = getattr(e, "code", None)
                is_transient = False

                if status_code is not None:
                    try:
                        status_code_int = int(status_code)
                        is_transient = status_code_int in {429, 500, 503, 504}
                    except ValueError:
                        is_transient = any(
                            err_str in str(status_code)
                            for err_str in ["429", "500", "503", "504"]
                        )
                else:
                    # Fallback string matching on message for transient patterns
                    msg = str(e).lower()
                    is_transient = any(
                        term in msg
                        for term in [
                            "rate limit",
                            "quota",
                            "too many requests",
                            "internal error",
                            "service unavailable",
                            "timeout",
                        ]
                    )

                if is_transient and attempt < self.max_retries:
                    logger.warning(
                        f"Transient Gemini API error (code={status_code}). "
                        f"Attempt {attempt + 1}/{self.max_retries + 1}. "
                        f"Retrying in {delay:.2f}s..."
                    )
                    time.sleep(delay)
                    delay *= 2
                else:
                    logger.error(f"Permanent Gemini API error or retries exhausted: {e}")
                    raise e

            except Exception as e:
                # Handle other transient failures (e.g. connection reset, DNS timeout)
                if attempt < self.max_retries:
                    logger.warning(
                        f"General network or client error: {e}. "
                        f"Attempt {attempt + 1}/{self.max_retries + 1}. "
                        f"Retrying in {delay:.2f}s..."
                    )
                    time.sleep(delay)
                    delay *= 2
                else:
                    logger.error(f"Max retries exceeded for general exception: {e}")
                    raise e

        raise RuntimeError("Failed to generate response: retry logic exhausted unexpectedly")
